apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server
  namespace: argo
  labels:
    app.kubernetes.io/name: argo-workflows-server
spec:
  ports:
  - port: 2746
    targetPort: 2746
  selector:
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/component: server
