---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share
  labels:
    type: local
spec:
  capacity:
    storage: 30Mi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/share/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
  namespace: argo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
